import PostSinglePage, { PostProps } from '@components/posts-single-page';
import { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import React from 'react';

const Post: NextPage<PostProps> = ({ data }) => {
  const metaTitle = `Anime | ${data.data.title}`;

  return (
    <>
      <Head>
        <title>{metaTitle}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <PostSinglePage data={data} />
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const currentId = context.query.postId as string;
  const res = await fetch(`https://api.jikan.moe/v4/anime/${currentId}`);
  const data = (await res.json()) as PostProps;

  return { props: { data } };
};

export default Post;
