import React from 'react';
import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';
import Layout from '@components/layout';
import RecommendedList, { PreviewItemType } from '@components/recommended-list';
import Pagination from '@components/pagination';
import { PostProps } from '@components/posts-single-page';

interface HomePageProps {
  data: {
    data: PreviewItemType[];
    pagination: {
      current_page: number;
      has_next_page: boolean;
    };
  };
}

const Home: NextPage<HomePageProps> = ({ data: { data, pagination } }) => {
  return (
    <div>
      <Head>
        <title>Anime</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Layout>
        {!!data.length && <RecommendedList items={data} />}
        <Pagination currentPage={pagination.current_page} hasNextPage={pagination.has_next_page} />
      </Layout>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const currentPage = (context.query.page || 1) as string;

  const res = await fetch(`https://api.jikan.moe/v4/top/anime?limit=9&page=${currentPage}`);
  const data = (await res.json()) as PostProps;

  return { props: { data } };
};

export default Home;
